stages:
  - install
  - deploy

cache:
  key: ${CI_BUILD_REF_NAME}
  paths:
    - node_modules/

install-staging:dep:
  stage: install
  tags:
    - cms_nginx
  only:
    - master
  script:
    - echo "=====start install======"
    - yarn install --registry https://registry.npm.taobao.org
    - echo "=====end install======"
  artifacts:
    expire_in: 30 days
    paths:
      - node_modules

deploy-staging:dep:
  stage: deploy
  tags:
    - cms_nginx
  only:
    - master
  script:
    - echo "=====start build======"
    - yarn run 'spa build'
    - echo "=====end build======"
    - echo "=====start deploy======"
    - sudo cp -rf ./dist/spa  /home/fsx/dev/nginx/dist
    - echo "=====end deploy======"
