version: "3"
services:
    quasar-template-spa:
        hostname: nginx
        container_name: quasar-template-spa
        image: nginx:latest
        # network_mode: "host"
        ports:
          - "80:80"
          - "443:443"
        volumes:
          - ./nginx.conf:/etc/nginx/nginx.conf
          - ./dist/:/usr/share/nginx/dist/
          - ./log/:/var/log/nginx/
          - ./ssl/:/etc/nginx/conf/ssl/
